author: RABE_IT Services
author_url: http://berndrabe.de
github_url: https://github.com/HHuckebein/Styling.git
exclude: [Styling/Support.swift, Styling/AppDelegate.swift, Styling/ViewController.swift]
copyright: '© 2016 [RABE_IT Services](http://berndrabe.de) under [open source license](https://github.com/HHuckebein/Styling/blob/master/LICENSE.txt).'
clean: true

swift_version: 3.0.2
